version: '3'

services:

  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/FileHandler
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_app
    hostname: redis
